[tool.black]
line-length = 100
target-version = ["py310", "py311", "py312"]

[tool.ruff]
line-length = 100
target-version = "py310"
select = ["E","F","I"]     # cơ bản: lỗi cú pháp, import, định dạng
exclude = ["dist","build",".venv"]