name: CI

on:
  push:
    branches: [main, dev, feature/**]
  pull_request:

permissions:
  contents: read
  actions: write # cần cho actions/upload-artifact@v4

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip" # cache pip theo requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Lint
        run: |
          ruff check .
          black --check .

      - name: Run tests + coverage (pytest)
        run: |
          pytest -q --maxfail=1 --disable-warnings \
            --cov=src --cov-report=xml:coverage.xml \
            --junitxml=test-results/junit.xml

      - name: Upload reports (junit + coverage)
        if: always() # luôn upload kể cả khi test fail
        uses: actions/upload-artifact@v4
        with:
          name: junit-and-coverage-py${{ matrix.python-version }}
          path: |
            test-results/junit.xml
            coverage.xml
          if-no-files-found: warn
          retention-days: 7
